using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SimpleVectors
{
    public interface IVector4<out T> : IVector4<IVector4<T>, T>
    {
    }

    public interface IVector4<out TVector4, out T> : IVector4<IVector2<T>, IVector3<T>, TVector4, T>, IVector3<T>
        where TVector4 : IVector4<IVector2<T>, IVector3<T>, TVector4, T>
    {
    }

    public interface IVector4<out TVector3, out TVector4, out T> : IVector4<IVector2<T>, TVector3, TVector4, T>, IVector3<TVector3, T>
        where TVector3 : IVector3<IVector2<T>, TVector3, T>
        where TVector4 : IVector4<IVector2<T>, TVector3, TVector4, T>
    {
    }

    public interface IVector4<out TVector2, out TVector3, out TVector4, out T> : IVector3<TVector2, TVector3, T>
        where TVector2 : IVector2<TVector2, T>
        where TVector3 : IVector3<TVector2, TVector3, T>
        where TVector4 : IVector4<TVector2, TVector3, TVector4, T>
    {
        T W { get; }
        TVector2 Xw { get; }
        TVector2 Yw { get; }
        TVector2 Zw { get; }
        TVector2 Wx { get; }
        TVector2 Wy { get; }
        TVector2 Wz { get; }
        TVector2 Ww { get; }

        TVector3 Xxw { get; }
        TVector3 Xyw { get; }
        TVector3 Xzw { get; }
        TVector3 Xwx { get; }
        TVector3 Xwy { get; }
        TVector3 Xwz { get; }
        TVector3 Xww { get; }
        TVector3 Yxw { get; }
        TVector3 Yyw { get; }
        TVector3 Yzw { get; }
        TVector3 Ywx { get; }
        TVector3 Ywy { get; }
        TVector3 Ywz { get; }
        TVector3 Yww { get; }
        TVector3 Zxw { get; }
        TVector3 Zyw { get; }
        TVector3 Zzw { get; }
        TVector3 Zwx { get; }
        TVector3 Zwy { get; }
        TVector3 Zwz { get; }
        TVector3 Zww { get; }
        TVector3 Wxx { get; }
        TVector3 Wxy { get; }
        TVector3 Wxz { get; }
        TVector3 Wxw { get; }
        TVector3 Wyx { get; }
        TVector3 Wyy { get; }
        TVector3 Wyz { get; }
        TVector3 Wyw { get; }
        TVector3 Wzx { get; }
        TVector3 Wzy { get; }
        TVector3 Wzz { get; }
        TVector3 Wzw { get; }
        TVector3 Wwx { get; }
        TVector3 Wwy { get; }
        TVector3 Wwz { get; }
        TVector3 Www { get; }

        TVector4 Xxxx { get; }
        TVector4 Xxxy { get; }
        TVector4 Xxxz { get; }
        TVector4 Xxxw { get; }
        TVector4 Xxyx { get; }
        TVector4 Xxyy { get; }
        TVector4 Xxyz { get; }
        TVector4 Xxyw { get; }
        TVector4 Xxzx { get; }
        TVector4 Xxzy { get; }
        TVector4 Xxzz { get; }
        TVector4 Xxzw { get; }
        TVector4 Xxwx { get; }
        TVector4 Xxwy { get; }
        TVector4 Xxwz { get; }
        TVector4 Xxww { get; }
        TVector4 Xyxx { get; }
        TVector4 Xyxy { get; }
        TVector4 Xyxz { get; }
        TVector4 Xyxw { get; }
        TVector4 Xyyx { get; }
        TVector4 Xyyy { get; }
        TVector4 Xyyz { get; }
        TVector4 Xyyw { get; }
        TVector4 Xyzx { get; }
        TVector4 Xyzy { get; }
        TVector4 Xyzz { get; }
        TVector4 Xyzw { get; }
        TVector4 Xywx { get; }
        TVector4 Xywy { get; }
        TVector4 Xywz { get; }
        TVector4 Xyww { get; }
        TVector4 Xzxx { get; }
        TVector4 Xzxy { get; }
        TVector4 Xzxz { get; }
        TVector4 Xzxw { get; }
        TVector4 Xzyx { get; }
        TVector4 Xzyy { get; }
        TVector4 Xzyz { get; }
        TVector4 Xzyw { get; }
        TVector4 Xzzx { get; }
        TVector4 Xzzy { get; }
        TVector4 Xzzz { get; }
        TVector4 Xzzw { get; }
        TVector4 Xzwx { get; }
        TVector4 Xzwy { get; }
        TVector4 Xzwz { get; }
        TVector4 Xzww { get; }
        TVector4 Xwxx { get; }
        TVector4 Xwxy { get; }
        TVector4 Xwxz { get; }
        TVector4 Xwxw { get; }
        TVector4 Xwyx { get; }
        TVector4 Xwyy { get; }
        TVector4 Xwyz { get; }
        TVector4 Xwyw { get; }
        TVector4 Xwzx { get; }
        TVector4 Xwzy { get; }
        TVector4 Xwzz { get; }
        TVector4 Xwzw { get; }
        TVector4 Xwwx { get; }
        TVector4 Xwwy { get; }
        TVector4 Xwwz { get; }
        TVector4 Xwww { get; }
        TVector4 Yxxx { get; }
        TVector4 Yxxy { get; }
        TVector4 Yxxz { get; }
        TVector4 Yxxw { get; }
        TVector4 Yxyx { get; }
        TVector4 Yxyy { get; }
        TVector4 Yxyz { get; }
        TVector4 Yxyw { get; }
        TVector4 Yxzx { get; }
        TVector4 Yxzy { get; }
        TVector4 Yxzz { get; }
        TVector4 Yxzw { get; }
        TVector4 Yxwx { get; }
        TVector4 Yxwy { get; }
        TVector4 Yxwz { get; }
        TVector4 Yxww { get; }
        TVector4 Yyxx { get; }
        TVector4 Yyxy { get; }
        TVector4 Yyxz { get; }
        TVector4 Yyxw { get; }
        TVector4 Yyyx { get; }
        TVector4 Yyyy { get; }
        TVector4 Yyyz { get; }
        TVector4 Yyyw { get; }
        TVector4 Yyzx { get; }
        TVector4 Yyzy { get; }
        TVector4 Yyzz { get; }
        TVector4 Yyzw { get; }
        TVector4 Yywx { get; }
        TVector4 Yywy { get; }
        TVector4 Yywz { get; }
        TVector4 Yyww { get; }
        TVector4 Yzxx { get; }
        TVector4 Yzxy { get; }
        TVector4 Yzxz { get; }
        TVector4 Yzxw { get; }
        TVector4 Yzyx { get; }
        TVector4 Yzyy { get; }
        TVector4 Yzyz { get; }
        TVector4 Yzyw { get; }
        TVector4 Yzzx { get; }
        TVector4 Yzzy { get; }
        TVector4 Yzzz { get; }
        TVector4 Yzzw { get; }
        TVector4 Yzwx { get; }
        TVector4 Yzwy { get; }
        TVector4 Yzwz { get; }
        TVector4 Yzww { get; }
        TVector4 Ywxx { get; }
        TVector4 Ywxy { get; }
        TVector4 Ywxz { get; }
        TVector4 Ywxw { get; }
        TVector4 Ywyx { get; }
        TVector4 Ywyy { get; }
        TVector4 Ywyz { get; }
        TVector4 Ywyw { get; }
        TVector4 Ywzx { get; }
        TVector4 Ywzy { get; }
        TVector4 Ywzz { get; }
        TVector4 Ywzw { get; }
        TVector4 Ywwx { get; }
        TVector4 Ywwy { get; }
        TVector4 Ywwz { get; }
        TVector4 Ywww { get; }
        TVector4 Zxxx { get; }
        TVector4 Zxxy { get; }
        TVector4 Zxxz { get; }
        TVector4 Zxxw { get; }
        TVector4 Zxyx { get; }
        TVector4 Zxyy { get; }
        TVector4 Zxyz { get; }
        TVector4 Zxyw { get; }
        TVector4 Zxzx { get; }
        TVector4 Zxzy { get; }
        TVector4 Zxzz { get; }
        TVector4 Zxzw { get; }
        TVector4 Zxwx { get; }
        TVector4 Zxwy { get; }
        TVector4 Zxwz { get; }
        TVector4 Zxww { get; }
        TVector4 Zyxx { get; }
        TVector4 Zyxy { get; }
        TVector4 Zyxz { get; }
        TVector4 Zyxw { get; }
        TVector4 Zyyx { get; }
        TVector4 Zyyy { get; }
        TVector4 Zyyz { get; }
        TVector4 Zyyw { get; }
        TVector4 Zyzx { get; }
        TVector4 Zyzy { get; }
        TVector4 Zyzz { get; }
        TVector4 Zyzw { get; }
        TVector4 Zywx { get; }
        TVector4 Zywy { get; }
        TVector4 Zywz { get; }
        TVector4 Zyww { get; }
        TVector4 Zzxx { get; }
        TVector4 Zzxy { get; }
        TVector4 Zzxz { get; }
        TVector4 Zzxw { get; }
        TVector4 Zzyx { get; }
        TVector4 Zzyy { get; }
        TVector4 Zzyz { get; }
        TVector4 Zzyw { get; }
        TVector4 Zzzx { get; }
        TVector4 Zzzy { get; }
        TVector4 Zzzz { get; }
        TVector4 Zzzw { get; }
        TVector4 Zzwx { get; }
        TVector4 Zzwy { get; }
        TVector4 Zzwz { get; }
        TVector4 Zzww { get; }
        TVector4 Zwxx { get; }
        TVector4 Zwxy { get; }
        TVector4 Zwxz { get; }
        TVector4 Zwxw { get; }
        TVector4 Zwyx { get; }
        TVector4 Zwyy { get; }
        TVector4 Zwyz { get; }
        TVector4 Zwyw { get; }
        TVector4 Zwzx { get; }
        TVector4 Zwzy { get; }
        TVector4 Zwzz { get; }
        TVector4 Zwzw { get; }
        TVector4 Zwwx { get; }
        TVector4 Zwwy { get; }
        TVector4 Zwwz { get; }
        TVector4 Zwww { get; }
        TVector4 Wxxx { get; }
        TVector4 Wxxy { get; }
        TVector4 Wxxz { get; }
        TVector4 Wxxw { get; }
        TVector4 Wxyx { get; }
        TVector4 Wxyy { get; }
        TVector4 Wxyz { get; }
        TVector4 Wxyw { get; }
        TVector4 Wxzx { get; }
        TVector4 Wxzy { get; }
        TVector4 Wxzz { get; }
        TVector4 Wxzw { get; }
        TVector4 Wxwx { get; }
        TVector4 Wxwy { get; }
        TVector4 Wxwz { get; }
        TVector4 Wxww { get; }
        TVector4 Wyxx { get; }
        TVector4 Wyxy { get; }
        TVector4 Wyxz { get; }
        TVector4 Wyxw { get; }
        TVector4 Wyyx { get; }
        TVector4 Wyyy { get; }
        TVector4 Wyyz { get; }
        TVector4 Wyyw { get; }
        TVector4 Wyzx { get; }
        TVector4 Wyzy { get; }
        TVector4 Wyzz { get; }
        TVector4 Wyzw { get; }
        TVector4 Wywx { get; }
        TVector4 Wywy { get; }
        TVector4 Wywz { get; }
        TVector4 Wyww { get; }
        TVector4 Wzxx { get; }
        TVector4 Wzxy { get; }
        TVector4 Wzxz { get; }
        TVector4 Wzxw { get; }
        TVector4 Wzyx { get; }
        TVector4 Wzyy { get; }
        TVector4 Wzyz { get; }
        TVector4 Wzyw { get; }
        TVector4 Wzzx { get; }
        TVector4 Wzzy { get; }
        TVector4 Wzzz { get; }
        TVector4 Wzzw { get; }
        TVector4 Wzwx { get; }
        TVector4 Wzwy { get; }
        TVector4 Wzwz { get; }
        TVector4 Wzww { get; }
        TVector4 Wwxx { get; }
        TVector4 Wwxy { get; }
        TVector4 Wwxz { get; }
        TVector4 Wwxw { get; }
        TVector4 Wwyx { get; }
        TVector4 Wwyy { get; }
        TVector4 Wwyz { get; }
        TVector4 Wwyw { get; }
        TVector4 Wwzx { get; }
        TVector4 Wwzy { get; }
        TVector4 Wwzz { get; }
        TVector4 Wwzw { get; }
        TVector4 Wwwx { get; }
        TVector4 Wwwy { get; }
        TVector4 Wwwz { get; }
        TVector4 Wwww { get; }
    }
}
